[package]
name = "parser_lib"
version = "0.0.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"

[dependencies]
mail-parser = { version = "0.8.0", default-features = false }
wasm-bindgen = "=0.2.83"
